/* config.h. Generated by cmake from config.h.cmake */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* dbus_threads_init_default (needs DBus >= 0.93) */
#cmakedefine DBUS_HAS_THREADS_INIT_DEFAULT

/* Define to enable debug build */
#cmakedefine DEBUG

/* to enable hidden symbols */
#cmakedefine GCC_HASCLASSVISIBILITY

/* Define to 1 if you have the <dlfcn.h> header file. */
#cmakedefine HAVE_DLFCN_H

/* Define to 1 if you have the <expat.h> header file. */
#cmakedefine HAVE_EXPAT_H

/* Define to 1 if you have the <inttypes.h> header file. */
#cmakedefine HAVE_INTTYPES_H

/* Define to 1 if you have the <memory.h> header file. */
#cmakedefine HAVE_MEMORY_H

/* Define if you have POSIX threads libraries and header files. */
#cmakedefine HAVE_PTHREAD

/* Define to enable pthread support */
#cmakedefine HAVE_PTHREAD_H

/* Define to 1 if you have the <stdint.h> header file. */
#cmakedefine HAVE_STDINT_H

/* Define to 1 if you have the <stdlib.h> header file. */
#cmakedefine HAVE_STDLIB_H

/* Define to 1 if you have the <strings.h> header file. */
#cmakedefine HAVE_STRINGS_H

/* Define to 1 if you have the <string.h> header file. */
#cmakedefine HAVE_STRING_H

/* Define to 1 if you have the <sys/stat.h> header file. */
#cmakedefine HAVE_SYS_STAT_H

/* Define to 1 if you have the <sys/types.h> header file. */
#cmakedefine HAVE_SYS_TYPES_H

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H

